# Create a 1000x1000x50 array with random values 

In [26]:
import numpy as np

np.random.rand(1000, 1000, 500)
print(np.random.rand(1000, 1000, 500))

[[[0.49424066 0.24653915 0.62930851 ... 0.44823386 0.98885541 0.35504514]
  [0.50000444 0.94849896 0.24700751 ... 0.11302992 0.27019794 0.89325971]
  [0.69532815 0.72896411 0.53088299 ... 0.08631615 0.74378216 0.26300103]
  ...
  [0.45295979 0.71262134 0.83278925 ... 0.72094074 0.85388657 0.13914399]
  [0.29376942 0.02956378 0.8971739  ... 0.75499892 0.22790854 0.84553081]
  [0.78196255 0.14887481 0.83244542 ... 0.30057864 0.8945114  0.56516768]]

 [[0.98304874 0.7242973  0.89093556 ... 0.78767101 0.28539418 0.68823198]
  [0.99604729 0.9850491  0.21757432 ... 0.93276426 0.04546211 0.31606404]
  [0.21849046 0.92239056 0.72325548 ... 0.66247704 0.90188903 0.18464718]
  ...
  [0.85712803 0.38437906 0.40578825 ... 0.9571012  0.38808837 0.51009941]
  [0.84724414 0.57171015 0.56481082 ... 0.98760553 0.99711606 0.01537881]
  [0.17534363 0.36214822 0.84419333 ... 0.59269351 0.87997841 0.63973576]]

 [[0.49190927 0.08466621 0.80491592 ... 0.11722538 0.86462011 0.58554724]
  [0.11503711 0.538636

# Create a null vector of size 10 but the fourth value which is 5

In [20]:
import numpy as np
null_vector = np.zeros(10)
print(null_vector)

null_vector[3] = 5
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]


# Create a 10x10 identity matrix

In [23]:
import numpy as np
identity_matrix_10x10 = np.identity(10, dtype = int)
print(identity_matrix_10x10)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


# Create a 6x6 array with random value from 1,10 and find the mean value

In [49]:
import numpy as np
sum = 0
average = 0

array_6x6 = np.random.randint(1, 10, size = (6, 6))
print(array_6x6)

for i in range(len(array_6x6)):
  for j in range(len(array_6x6[i])):
    sum += array_6x6[i][j]
    
average = sum / (6 * 6)
print(average)



[[8 4 3 2 6 9]
 [4 1 4 8 5 1]
 [3 5 2 5 5 5]
 [9 4 2 4 7 1]
 [3 1 2 7 6 4]
 [1 3 5 2 4 5]]
4.166666666666667


# Create a 5x5 matrix with random value and change diagonal values with 1,2,3,4,5

In [51]:
import numpy as np

array_5x5 = np.random.randint(1, 10, size = (5, 5))
print(array_5x5, end = "\n\n")

array_5x5[0][0] = 1
array_5x5[1][1] = 2
array_5x5[2][2] = 3
array_5x5[3][3] = 4
array_5x5[4][4] = 5

print(array_5x5)

[[5 1 6 8 2]
 [7 2 3 8 7]
 [9 4 6 7 5]
 [4 4 3 2 2]
 [3 9 1 1 8]]

[[1 1 6 8 2]
 [7 2 3 8 7]
 [9 4 3 7 5]
 [4 4 3 4 2]
 [3 9 1 1 5]]


# create a 5x3 matrix and a 3x2 matrix and multiply them (matrix product)

In [57]:
import numpy as np

array_5x3 = np.random.randint(1, 10, size = (5, 3))
print(array_5x3, end = "\n\n")
array_3x2 = np.random.randint(1, 10, size = (3, 2))
print(array_3x2, end = "\n\n")

print(np.dot(array_5x3, array_3x2))

[[4 5 3]
 [5 9 7]
 [4 9 9]
 [9 9 8]
 [3 3 7]]

[[2 7]
 [8 7]
 [2 4]]

[[ 54  75]
 [ 96 126]
 [ 98 127]
 [106 158]
 [ 44  70]]


# Compute ((A+B)*(-A/2)) 

In [59]:
a = np.array([[3, 2],
       [1, 2]])
b = np.array([[1, 1],
       [2, 2]])

print(a, end = "\n\n")
print(b, end = "\n\n")

print((a + b) * (-a / 2))

[[3 2]
 [1 2]]

[[1 1]
 [2 2]]

[[-6.  -3. ]
 [-1.5 -4. ]]


# get the inter values from array Z

In [62]:
Z = np.array([7.0799411 , 0.49711506, 0.12911289, 1.4150807 , 7.05211707, 2.24443288, 3.36291566, 7.27380129, 2.14662932, 5.62338762])
print(Z)

#expected output :
    #[7. 0. 0. 1. 7. 2. 3. 7. 2. 5.]
    
for i in range(len(Z)):
    Z[i] = int(Z[i])
    
print(Z)

[7.0799411  0.49711506 0.12911289 1.4150807  7.05211707 2.24443288
 3.36291566 7.27380129 2.14662932 5.62338762]
[7. 0. 0. 1. 7. 2. 3. 7. 2. 5.]


# Create a 4x4 matrix with row values ranging from 0 to 3

expected output

            [[0. 1. 2. 3.]
             [0. 1. 2. 3.]
             [0. 1. 2. 3.]
             [0. 1. 2. 3.]]

In [71]:
import numpy as np
array_4x4 = np.zeros((4, 4))
print(array_4x4, end = "\n\n")

for i in range(4):
    for j in range(4):
        array_4x4[i][j] = random.randint(0, 3)
        
print(array_4x4, end = "\n\n")

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[3. 1. 3. 3.]
 [2. 3. 1. 2.]
 [2. 0. 2. 1.]
 [3. 2. 3. 3.]]



# Create a random vector of size 6 and sort it 

In [77]:
import numpy as np
null_vector = np.zeros(6)

for i in range(len(null_vector)):
    null_vector[i] = len(null_vector) - i

print(null_vector)
print(np.sort(null_vector))


[6. 5. 4. 3. 2. 1.]
[1. 2. 3. 4. 5. 6.]


# Subtract the mean of each row of a matrix 

In [106]:
import numpy

X = np.array([[9, 5, 7, 7, 8],
       [5, 9, 5, 5, 5],
       [5, 9, 8, 8, 9],
       [7, 5, 5, 7, 9],
       [6, 9, 9, 7, 9]])

sum_row = [0, 0, 0, 0, 0]
means = [0, 0, 0, 0, 0]
element_count = 1

for i in range(5):
    for j in range(5):
        print(X[i][j], end = " ")
        sum_row[i] += X[i][j]
    print(sum_row[i])
    
print(sum_row)

for i in range(len(sum_row)):
    means[i] = sum_row[i] / 5.0
    
print(means)

for i in range(5):
    for j in range(5):
        X[i][j] = X[i][j] - means[j]

print(X)

9 5 7 7 8 36
5 9 5 5 5 29
5 9 8 8 9 39
7 5 5 7 9 33
6 9 9 7 9 40
[36, 29, 39, 33, 40]
[7.2, 5.8, 7.8, 6.6, 8.0]
[[ 1  0  0  0  0]
 [-2  3 -2 -1 -3]
 [-2  3  0  1  1]
 [ 0  0 -2  0  1]
 [-1  3  1  0  1]]


In [93]:
expected output

array([[ 1.8, -0.8, -0.8,  0.4,  0. ],
       [-2.2,  3.2, -2.8, -1.6, -3. ],
       [-2.2,  3.2,  0.2,  1.4,  1. ],
       [-0.2, -0.8, -2.8,  0.4,  1. ],
       [-1.2,  3.2,  1.2,  0.4,  1. ]])

SyntaxError: invalid syntax (360555450.py, line 1)

# Given an array

In [48]:
Z = np.array([[[[12, 19, 13, 14, 19],
         [ 9, 19, 13,  6, 16],
         [11, 10, 14, 17, 17],
         [16,  7, 18, 10, 12],
         [15, 19,  5, 14, 11]],

        [[16, 15, 15, 13,  7],
         [16, 19,  9, 10, 15],
         [16, 14,  7,  9,  7],
         [18,  8,  9, 18,  7],
         [16, 11,  9, 12, 15]]],


       [[[12, 16, 11,  8,  6],
         [12,  6, 18, 17, 18],
         [12,  9, 19,  7, 19],
         [ 6,  6,  7,  9,  9],
         [19, 13, 11, 18, 13]],

        [[16, 17,  8, 12, 16],
         [16, 11,  8, 17,  5],
         [11, 18, 11, 18, 10],
         [13,  8, 12,  6,  7],
         [ 9, 18, 19, 19,  9]]]])


get [15, 9, 9,7]

get [19, 9, 10
     14, 7, 9
     8, 9, 18]
     
get [11, 8, 6
     19, 7, 19
     7, 9, 9]
     


# Sigmoid function

$$sigmoid(x) = 1 / (1 + e⁻ˣ)$$

expected output:


    sigmoid(-1) = 0.2689414213699951

# Tanh function

$$tanh(x)=\frac{exp(-x)}{(1+exp(-x))²}$$

expected output:
    
       tanh(-5) = -0.999909204262595

# Derivative of tanh function


$$df(x)=[\frac{1}{(1+exp(-x))}]*[\frac{1}{(1/(1+exp(-x))}]$$


expected output:
    
       d_tanh(-1) = 0.41997434161402614

# Linear regression cost function

The equation for cost with one variable is:
  $$J(w,b) = \frac{1}{2m} \sum\limits_{i = 0}^{m-1} (f_{w,b}(x^{(i)}) - y^{(i)})^2 \tag{1}$$ 
 
where 
  $$f_{w,b}(x^{(i)}) = wx^{(i)} + b \tag{2}$$
  


x_train = np.array([1.0, 2.0])  

m = x_train.shape[0]

y_train = np.array([300.0, 500.0])

w = np.array([150])

b = 150

#expected output

    compute_cost(x_train, y_train, w, b) = array([625.])